

//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class ACCEDER_APPLICATION
{

    public decimal PERSONNEL_ID { get; set; }

    public decimal APPLICATION_ID { get; set; }

}


public partial class ACCEDER_APPLICATION2
{

    public decimal PERSONNEL_ID { get; set; }

    public decimal APPLICATION_ID { get; set; }

}


public partial class ACCEDER_APPLICATION3
{

    public decimal PERSONNEL_ID { get; set; }

    public decimal APPLICATION_ID { get; set; }

}


public partial class ACCES_APPLICATION
{

    public decimal APPLICATION_ID { get; set; }

    public string APPLICATION_NOM { get; set; }

}


public partial class BUREAU_ETUDE
{

    public decimal PERSONNEL_ID { get; set; }

    public string SPECIALISATION { get; set; }

    public string PERSONNEL_LOGIN { get; set; }

    public string PERSONNEL_MDP { get; set; }

    public string PERSONNEL_TOKEN { get; set; }

    public string PERSONNEL_NOM { get; set; }

    public string PERSONNEL_PRENOM { get; set; }

}


public partial class CLIENT
{

    public decimal CLIENT_ID { get; set; }

    public string CLIENT_REFERENCE { get; set; }

}


public partial class COMMANDE
{

    public decimal COMMANDE_ID { get; set; }

    public Nullable<System.DateTime> COMMANDE_DATE { get; set; }

    public Nullable<short> COMMANDE_STATUT { get; set; }

}


public partial class COMMERCIAL
{

    public decimal PERSONNEL_ID { get; set; }

    public string SECTEUR { get; set; }

    public string NUMERO_MOBILE { get; set; }

    public string PERSONNEL_LOGIN { get; set; }

    public string PERSONNEL_MDP { get; set; }

    public string PERSONNEL_TOKEN { get; set; }

    public string PERSONNEL_NOM { get; set; }

    public string PERSONNEL_PRENOM { get; set; }

}


public partial class COMPOSANT
{

    public decimal COMPOSANT_ID { get; set; }

    public decimal TYPE_COMPOSANT { get; set; }

    public decimal FOURNISSEUR_ID { get; set; }

    public string COMPOSANT_NOM { get; set; }

    public Nullable<int> COMPOSANT_STOCK { get; set; }

    public Nullable<decimal> COMPOSANT_VALEUR_CARACTERISTIQUE_1 { get; set; }

    public Nullable<decimal> COMPOSANT_VALEUR_CARACTERISTIQUE_2 { get; set; }

}


public partial class COMPOSANT_IMAGE
{

    public decimal FICHIER_ID { get; set; }

    public decimal COMPOSANT_ID { get; set; }

}


public partial class COMPTABLE
{

    public decimal PERSONNEL_ID { get; set; }

    public string NUMERO_POSTE { get; set; }

    public string PERSONNEL_LOGIN { get; set; }

    public string PERSONNEL_MDP { get; set; }

    public string PERSONNEL_TOKEN { get; set; }

    public string PERSONNEL_NOM { get; set; }

    public string PERSONNEL_PRENOM { get; set; }

}


public partial class CONTACT_CLIENT
{

    public decimal CONTACT_ID { get; set; }

    public decimal CLIENT_ID { get; set; }

    public string CONTACT_NOM { get; set; }

    public string CONTACT_TELEPHONE { get; set; }

    public string CONTACT_MAIL { get; set; }

    public string CONTACT_ADRESSE { get; set; }

    public string CONTACT_ADRESSE2 { get; set; }

    public string CONTACT_CP { get; set; }

    public string CONTACT_VILLE { get; set; }

    public string CONTACT_CLIENT_SITUATION_MATRIMONIALE { get; set; }

}


public partial class CONTACT_FOURNISSEUR
{

    public decimal CONTACT_ID { get; set; }

    public decimal FOURNISSEUR_ID { get; set; }

    public string CONTACT_NOM { get; set; }

    public string CONTACT_TELEPHONE { get; set; }

    public string CONTACT_MAIL { get; set; }

    public string CONTACT_ADRESSE { get; set; }

    public string CONTACT_ADRESSE2 { get; set; }

    public string CONTACT_CP { get; set; }

    public string CONTACT_VILLE { get; set; }

    public string CONTACT_FOURNISSEUR_POSTE { get; set; }

}


public partial class CONTENIR
{

    public decimal PRODUIT_ID { get; set; }

    public decimal MODELE_GAMME_ID { get; set; }

}


public partial class DEVIS
{

    public decimal DEVIS_ID { get; set; }

    public decimal CLIENT_ID { get; set; }

    public decimal PERSONNEL_ID { get; set; }

    public decimal BUR_PERSONNEL_ID { get; set; }

    public decimal COM_PERSONNEL_ID { get; set; }

    public Nullable<decimal> DEVIS_ESTIMATION_PRIX { get; set; }

    public Nullable<System.DateTime> DEVIS_DATE { get; set; }

    public string DEVIS_NOM_PROJET { get; set; }

    public string DEVIS_REFERENCE { get; set; }

    public Nullable<short> DEVIS_ETAT { get; set; }

}


public partial class EST_COUPE_DE_PRINCIPE
{

    public decimal FICHIER_ID { get; set; }

    public decimal MODULE_ID { get; set; }

}


public partial class EST_DISPONIBLE
{

    public decimal MODULE_ID { get; set; }

    public decimal GAMME_ID { get; set; }

}


public partial class EST_FICHIER_DEVIS
{

    public decimal FICHIER_ID { get; set; }

    public decimal DEVIS_ID { get; set; }

    public decimal TYPE_FICHIER_ID { get; set; }

}


public partial class EST_RESPONSABLE
{

    public decimal PERSONNEL_ID { get; set; }

    public decimal COMPOSANT_ID { get; set; }

}


public partial class ETAPE_ECHELONNEMENT
{

    public decimal ETAPE_ECHELONNEMENT_ID { get; set; }

    public string ETAPE_ECHELONNEMENT_NOM { get; set; }

    public Nullable<int> ETAPE_ECHELONNEMENT_ORDRE { get; set; }

}


public partial class FAIRE_PARTIE
{

    public decimal GAMME_ID { get; set; }

    public decimal FINITION_ID { get; set; }

}


public partial class FICHIER
{

    public decimal FICHIER_ID { get; set; }

    public decimal TYPE_FICHIER_ID { get; set; }

    public string FICHIER_NOM { get; set; }

    public string FICHIER_CHEMIN { get; set; }

    public Nullable<int> FICHIER_POIDS { get; set; }

}


public partial class FINITION
{

    public decimal FINITION_ID { get; set; }

    public decimal TYPE_FINITION_ID { get; set; }

    public string FINITION_NOM { get; set; }

    public string FINITION_DESCRIPTION { get; set; }

}


public partial class FINITION_IMAGE
{

    public decimal FINITION_ID { get; set; }

    public decimal FICHIER_ID { get; set; }

}


public partial class FOURNISSEUR
{

    public decimal FOURNISSEUR_ID { get; set; }

    public string FOURNISSEUR_SIRET { get; set; }

    public string FOURNISSEUR_SIREN { get; set; }

}


public partial class GAMME
{

    public decimal GAMME_ID { get; set; }

    public string GAMME_NOM { get; set; }

    public string GAMME_DESCRIPTION { get; set; }

}


public partial class LIER_FINITION
{

    public decimal FINITION_ID { get; set; }

    public decimal MODELE_GAMME_ID { get; set; }

}


public partial class LIER_MODULE
{

    public decimal MODULE_ID { get; set; }

    public decimal MODELE_GAMME_ID { get; set; }

    public string IDENTIFICATION { get; set; }

    public string SECTION { get; set; }

    public Nullable<int> LONGUEUR { get; set; }

    public Nullable<int> HAUTEUR { get; set; }

}


public partial class LIGNE_COMMANDE
{

    public decimal COMMANDE_ID { get; set; }

    public decimal COMPOSANT_ID { get; set; }

    public decimal FOURNISSEUR_ID { get; set; }

    public Nullable<decimal> PRIX_ACHAT { get; set; }

    public Nullable<int> QUANTITE_LIGNE_COMMANDE { get; set; }

}


public partial class MODELE_DE_GAMME
{

    public decimal MODELE_GAMME_ID { get; set; }

    public decimal GAMME_ID { get; set; }

    public decimal TYPE_MODELE_GAMME_ID { get; set; }

    public Nullable<bool> EST_PAR_DEFAUT { get; set; }

    public string MODELE_GAMME_NOM { get; set; }

    public string MODELE_GAMME_DESCRIPTION { get; set; }

    public Nullable<int> MODELE_GAMME_NB_PIECES { get; set; }

    public string MODELE_GAMME_SURFACE { get; set; }

}


public partial class MODELE_GAMME_IMAGE
{

    public decimal MODELE_GAMME_ID { get; set; }

    public decimal FICHIER_ID { get; set; }

}


public partial class MODULE
{

    public decimal MODULE_ID { get; set; }

    public Nullable<decimal> MOD_MODULE_ID { get; set; }

    public decimal TYPE_MODULE_ID { get; set; }

    public decimal PERSONNEL_ID { get; set; }

    public string MODULE_NOM { get; set; }

    public string MODULE_TYPE { get; set; }

    public Nullable<decimal> MODULE_MARGE_COMMERCIAL { get; set; }

    public Nullable<decimal> MODULE_MARGE_ENTREPRISE { get; set; }

    public Nullable<decimal> QUANTITE_PARENT { get; set; }

}


public partial class PAYER
{

    public decimal ETAPE_ECHELONNEMENT_ID { get; set; }

    public decimal DEVIS_ID { get; set; }

    public Nullable<decimal> POURCENTAGE_ETAPE { get; set; }

    public Nullable<bool> STATUT_PAIEMENT { get; set; }

    public Nullable<System.DateTime> DATE_ECHEANCE { get; set; }

    public Nullable<System.DateTime> DATE_PAIEMENT { get; set; }

    public Nullable<decimal> MONTANT_PAYER { get; set; }

}


public partial class PEUT_APPLIQUER
{

    public decimal MODULE_ID { get; set; }

    public decimal FINITION_ID { get; set; }

}


public partial class PRODUIT
{

    public decimal PRODUIT_ID { get; set; }

    public decimal DEVIS_ID { get; set; }

    public decimal GAMME_ID { get; set; }

    public string PRODUIT_NOM { get; set; }

    public string PRODUIT_DESCRIPTION { get; set; }

}


public partial class TYPE_COMPOSANT
{

    public decimal TYPE_COMPOSANT1 { get; set; }

    public string TYPE_COMPOSANT_NOM { get; set; }

    public string TYPE_COMPOSANT_CARACTERISTIQUE { get; set; }

    public string TYPE_COMPOSANT_UNITE_USAGE { get; set; }

}


public partial class TYPE_FICHIER
{

    public decimal TYPE_FICHIER_ID { get; set; }

    public string TYPE_FICHIER_NOM { get; set; }

}


public partial class TYPE_FINITION
{

    public decimal TYPE_FINITION_ID { get; set; }

    public string TYPE_FINITION_NOM { get; set; }

}


public partial class TYPE_MODELE_GAMME
{

    public decimal TYPE_MODELE_GAMME_ID { get; set; }

    public string TYPE_MODELE_GAMME_NOM { get; set; }

}


public partial class TYPE_MODULE
{

    public decimal TYPE_MODULE_ID { get; set; }

    public string TYPE_MODULE_NOM { get; set; }

    public string TYPE_MODULE_UNITE_USAGE { get; set; }

    public string TYPE_MODULE_CARACTERISTIQUE { get; set; }

}


public partial class UTILISER___COUPE_DE_PRINCIPE
{

    public decimal MODULE_ID { get; set; }

    public decimal COMPOSANT_ID { get; set; }

    public Nullable<int> QUANTITE_COUPE { get; set; }

}

