//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class maderaEntities : DbContext
{
    public maderaEntities()
        : base("name=maderaEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<ACCEDER_APPLICATION> ACCEDER_APPLICATION { get; set; }
    public virtual DbSet<ACCEDER_APPLICATION2> ACCEDER_APPLICATION2 { get; set; }
    public virtual DbSet<ACCEDER_APPLICATION3> ACCEDER_APPLICATION3 { get; set; }
    public virtual DbSet<ACCES_APPLICATION> ACCES_APPLICATION { get; set; }
    public virtual DbSet<BUREAU_ETUDE> BUREAU_ETUDE { get; set; }
    public virtual DbSet<CLIENT> CLIENT { get; set; }
    public virtual DbSet<COMMANDE> COMMANDE { get; set; }
    public virtual DbSet<COMMERCIAL> COMMERCIAL { get; set; }
    public virtual DbSet<COMPOSANT> COMPOSANT { get; set; }
    public virtual DbSet<COMPOSANT_IMAGE> COMPOSANT_IMAGE { get; set; }
    public virtual DbSet<COMPTABLE> COMPTABLE { get; set; }
    public virtual DbSet<CONTACT_CLIENT> CONTACT_CLIENT { get; set; }
    public virtual DbSet<CONTACT_FOURNISSEUR> CONTACT_FOURNISSEUR { get; set; }
    public virtual DbSet<CONTENIR> CONTENIR { get; set; }
    public virtual DbSet<DEVIS> DEVIS { get; set; }
    public virtual DbSet<EST_COUPE_DE_PRINCIPE> EST_COUPE_DE_PRINCIPE { get; set; }
    public virtual DbSet<EST_DISPONIBLE> EST_DISPONIBLE { get; set; }
    public virtual DbSet<EST_FICHIER_DEVIS> EST_FICHIER_DEVIS { get; set; }
    public virtual DbSet<EST_RESPONSABLE> EST_RESPONSABLE { get; set; }
    public virtual DbSet<ETAPE_ECHELONNEMENT> ETAPE_ECHELONNEMENT { get; set; }
    public virtual DbSet<FAIRE_PARTIE> FAIRE_PARTIE { get; set; }
    public virtual DbSet<FICHIER> FICHIER { get; set; }
    public virtual DbSet<FINITION> FINITION { get; set; }
    public virtual DbSet<FINITION_IMAGE> FINITION_IMAGE { get; set; }
    public virtual DbSet<FOURNISSEUR> FOURNISSEUR { get; set; }
    public virtual DbSet<GAMME> GAMME { get; set; }
    public virtual DbSet<LIER_FINITION> LIER_FINITION { get; set; }
    public virtual DbSet<LIER_MODULE> LIER_MODULE { get; set; }
    public virtual DbSet<LIGNE_COMMANDE> LIGNE_COMMANDE { get; set; }
    public virtual DbSet<MODELE_DE_GAMME> MODELE_DE_GAMME { get; set; }
    public virtual DbSet<MODELE_GAMME_IMAGE> MODELE_GAMME_IMAGE { get; set; }
    public virtual DbSet<MODULE> MODULE { get; set; }
    public virtual DbSet<PAYER> PAYER { get; set; }
    public virtual DbSet<PEUT_APPLIQUER> PEUT_APPLIQUER { get; set; }
    public virtual DbSet<PRODUIT> PRODUIT { get; set; }
    public virtual DbSet<TYPE_COMPOSANT> TYPE_COMPOSANT { get; set; }
    public virtual DbSet<TYPE_FICHIER> TYPE_FICHIER { get; set; }
    public virtual DbSet<TYPE_FINITION> TYPE_FINITION { get; set; }
    public virtual DbSet<TYPE_MODELE_GAMME> TYPE_MODELE_GAMME { get; set; }
    public virtual DbSet<TYPE_MODULE> TYPE_MODULE { get; set; }
    public virtual DbSet<UTILISER___COUPE_DE_PRINCIPE> UTILISER___COUPE_DE_PRINCIPE { get; set; }
}
